namespace:
  name: suyash-ns

replicas: 3

labels:
  app: web

container:
  name: ghee-container
  port: 5656

service:
  name: ghee-service
  type: LoadBalancer
  port: 5656
  targetPort: 5656

configMap:
  name: suyash-configmap
  data:
    DB_HOST: "Mongodb"
    DB_PORT: "27017"
    DB_USER: "admin"
    APP_NAME: "ghee"
    APP_PORT: "5656"

secret:
  name: suyash-secret
  type: Opaque
  data:
    DB_user: QURNSU4=
    DB_password: UEFTU1dPUkQ=