apiVersion: v1
kind: Service

metadata:
  name: suyash-service

spec:
  type: LoadBalancer

  selector:
    app: web

  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000